# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "75d6f48b7607e5b8800206b6101c674b"
name = "ui-dashboard"
handle = "ui-dashboard-2"
application_url = "https://publishing-formatting-latina-dude.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://publishing-formatting-latina-dude.trycloudflare.com/auth/callback",
  "https://publishing-formatting-latina-dude.trycloudflare.com/auth/shopify/callback",
  "https://publishing-formatting-latina-dude.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
